name: gmail-sorter
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.13
  - scikit-learn=1.6.1
  - pandas=2.2.2
  - matplotlib=3.10.0
  - seaborn=0.13.2
  - pip
  - pip:
      - transformers==4.52.4
      - datasets==2.14.4
      - wandb==0.20.1